<?xml version="1.0"?>
<package format="3">
  <name>minot</name>
  <version>0.11.0</version>
  <description>A versatile toolset for debugging and verifying stateful robot perception software.</description>
  <maintainer email="stelzo@steado.de">stelzo</maintainer>
  <author email="stelzo@steado.de">stelzo</author>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>cargo</build_depend>
  <build_depend>python3-catkin-pkg-modules</build_depend>
  <build_depend>libclang-dev</build_depend>

  <build_depend>rcl</build_depend>
  <build_depend>rcl_action</build_depend>
  <build_depend>builtin_interfaces</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>rosgraph_msgs</build_depend>

  <exec_depend>rcl</exec_depend>
  <exec_depend>rcl_action</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

