# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
# Docs Workflow for Minot. The schema is used until there is one for Forgejo.

name: Docs

on:
  push:
    paths:
      - docs/**
      - .forgejo/workflows/docs.yml
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-dev-resolute
    steps:
      - uses: actions/checkout@v4
      - run: cd docs && uvx zensical build --clean
      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: https://${{ forge.repository_owner }}.codeberg.page/minot/
          token: ${{ forge.token }}
          source: docs/site/
