use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use anyhow::anyhow;
use clap::Parser;
use log::{debug, error, info, warn};
use sea::net::Packet;
use sea::{coordinator::CoordinatorImpl, net::PacketKind};

use mtc::{ActionPlan, COMPARE_NODE_NAME, Rules, VariableHistory};
use sea::{Coordinator, WindData};

#[derive(Parser, Debug)]
#[command(version, about, author, long_about = None)]
/// Minot Coordinator — Network Manager for Ratpub Nodes
pub struct Args {
    /// Path to .mt file for initialization
    pub file: Option<PathBuf>,
}

pub fn topic_from_eval_or_default(
    eval: &mtc::Evaluated,
    path: &str,
    default: &str,
) -> anyhow::Result<String> {
    let topic = eval.vars.resolve(path)?;
    if let Some(topic) = topic {
        match topic {
            mtc::Rhs::Path(topic) | mtc::Rhs::Val(mtc::Val::StringVal(topic)) => Ok(topic),
            _ => {
                Err(anyhow!("Expected String or Path for sending lidar topic"))
            }
        }
    } else {
        Ok(default.to_owned())
    }
}

#[derive(Debug)]
enum MinotTask {
    AppendRule {
        variable: String,
        commands: Vec<mtc::VariableHuman>,
    },
    LockNext {
        unlock_first: bool,
    },
    RulesClear,
    SendRatAction {
        ship_name: String,
        data: ActionPlan,
    },
    SendWind {
        ship_name: String,
        data: Vec<sea::WindData>,
    },
    WindDynamicVarReq(String), // Target is always Minot TUI
    Unlock,
    RegisterShipAtVar {
        ship: String,
        var: String,
        kind: sea::net::RatPubRegisterKind,
    },
}

#[derive(Debug)]
enum WindTaskKind {
    Fix(Vec<WindData>),
    Dynamic,
}

#[derive(Debug)]
struct WindTask {
    kind: WindTaskKind,
    already_seen: bool,
}

pub fn run_coordinator(locked_start: bool, clients: HashSet<String>, rules: Rules) {
    // Early port availability check for the fixed UDP listener port (CLIENT_LISTEN_PORT).
    // If already in use, clear the previous line (compile/search feedback) and print a user-friendly
    // English message, then exit. This ensures the TUI presents the error instead of an internal panic.
    {
        use std::net::UdpSocket;
        let port = sea::net::CLIENT_LISTEN_PORT;
        let addr = format!("0.0.0.0:{}", port);
        match UdpSocket::bind(&addr) {
            Ok(socket) => {
                // drop immediately – we only probe availability
                drop(socket);
            }
            Err(e) => {
                if e.kind() == std::io::ErrorKind::AddrInUse {
                    println!(
                        "Another Minot coordinator is running. Please terminate it before starting a new instance.");
                    std::process::exit(1);
                } else {
                    println!(
                        "Failed to bind coordinator UDP port {} ({}). Aborting startup.",
                        port, e
                    );
                    std::process::exit(1);
                }
            }
        }
    }
    let clients_wait_for_ack = std::sync::Arc::new(std::sync::RwLock::new(!clients.is_empty()));
    let rules = std::sync::Arc::new(std::sync::RwLock::new(rules));
    let rules_changer = std::sync::Arc::clone(&rules);

    let winds_var = std::sync::Arc::new(std::sync::RwLock::new(
        HashMap::<String, Vec<WindTask>>::new(),
    ));
    let winds_changer = std::sync::Arc::clone(&winds_var);

    let (wind_tx, _) = tokio::sync::broadcast::channel::<Vec<sea::WindData>>(20);

    // Task for centralized coordinator task work that is generated by the tasks implemented after this
    let (coord_tx, mut coord_rx) = tokio::sync::mpsc::unbounded_channel::<MinotTask>();
    let coord_tx_new_client = coord_tx.clone();
    let cwa_write = std::sync::Arc::clone(&clients_wait_for_ack);
    tokio::spawn(async move {
        let coordinator =
            std::sync::Arc::new(CoordinatorImpl::new(None, clients_wait_for_ack).await);

        // unlock clients to send us stuff when all our expected clients are connected
        let total_clients_check_rats = std::sync::Arc::clone(&coordinator.rat_qs);
        let (clients_collected_tx, mut clients_collected_rx) = tokio::sync::mpsc::channel(1);
        tokio::spawn(async move {
            debug!("waiting for all clients to be connected");
            CoordinatorImpl::ensure_clients_connected(total_clients_check_rats.clone(), clients)
                .await;
            debug!("all clients connected, sending ack to clients.");
            clients_collected_tx.send(()).await.unwrap();
            let clients = total_clients_check_rats.read().await;
            let ack = sea::net::Packet {
                header: sea::net::Header::default(),
                data: sea::net::PacketKind::Acknowledge,
            };
            for (_client_name, client) in clients.iter() {
                if let Err(e) = client.sender.send(ack.clone()).await {
                    error!("Could not send ack to unlock client: {e}");
                }
            }
            // allow other clients to join after all predefined clients are connected
            let mut cwa = cwa_write.write().unwrap();
            *cwa = false;
        });

        let mut new_clients_chan = coordinator.sea.network_clients_chan.subscribe();
        // Spawn a task for each rat or wind to listen when variables come in
        // TODO maybe also await until clients are collected so we can remove this task since all tasks that are needed for long term have been spawned
        let minot_client_connected = std::sync::Arc::new(std::sync::RwLock::new(false));
        let tasks_minot_connect = std::sync::Arc::clone(&minot_client_connected);
        let rules_change_for_disconnect = std::sync::Arc::clone(&rules_changer);
        tokio::spawn(async move {
            loop {
                match new_clients_chan.recv().await {
                    Ok(client) => {
                        let wind_tx_inner = wind_tx.clone();
                        match client.name {
                            sea::ShipKind::Rat(name) => {
                                if name == COMPARE_NODE_NAME {
                                    let mut lock = tasks_minot_connect.write().unwrap();
                                    *lock = true;
                                    // TODO handle set false when disconnected
                                }
                                let mut client_news = client.recv.subscribe();
                                let inner_name = name.clone();
                                let rat_rules = std::sync::Arc::clone(&rules);
                                let rat_coord_tx = coord_tx_new_client.clone();
                                let winds_inner = std::sync::Arc::clone(&winds_changer);
                                let rules_change_for_disconnect_inner = std::sync::Arc::clone(&rules_change_for_disconnect);
                                // spawn task to handle variable requests for this rat
                                tokio::spawn(async move {
                                    let minot_compare_name = COMPARE_NODE_NAME.to_string();
                                    match inner_name.as_str() {
                                        COMPARE_NODE_NAME => loop {
                                            match client_news.recv().await {
                                                Ok((packet, _)) => match packet.data {
                                                    PacketKind::RuleAppend {
                                                        variable,
                                                        commands,
                                                    } => {
                                                        rat_coord_tx
                                                            .send(MinotTask::AppendRule {
                                                                variable,
                                                                commands,
                                                            })
                                                            .unwrap();
                                                    }
                                                    PacketKind::RulesClear => {
                                                        rat_coord_tx
                                                            .send(MinotTask::RulesClear)
                                                            .unwrap();
                                                    }
                                                    PacketKind::LockNext { unlock_first } => {
                                                        rat_coord_tx
                                                            .send(MinotTask::LockNext {
                                                                unlock_first,
                                                            })
                                                            .unwrap();
                                                    }
                                                    PacketKind::Unlock => {
                                                        rat_coord_tx
                                                            .send(MinotTask::Unlock)
                                                            .unwrap();
                                                    }
                                                    PacketKind::WindDynamic(var) => {
                                                        let mut w = winds_inner.write().unwrap();
                                                        let ty = WindTask {
                                                            already_seen: false,
                                                            kind: WindTaskKind::Dynamic,
                                                        };
                                                        match w.get_mut(&var) {
                                                            Some(wts) => {
                                                                wts.push(ty);
                                                            }
                                                            None => {
                                                                w.insert(var, vec![ty]);
                                                            }
                                                        }
                                                    }
                                                    PacketKind::Wind(bwd) => {
                                                        let mut send_now =
                                                            Vec::with_capacity(bwd.len());
                                                        for wd in bwd {
                                                            match wd.at_var {
                                                                Some(var) => {
                                                                    let mut w = winds_inner
                                                                        .write()
                                                                        .unwrap();
                                                                    match w.get_mut(&var) {
                                                                        Some(wt) => {
                                                                            wt.push(WindTask { kind: WindTaskKind::Fix(vec![wd.data]), already_seen: false });
                                                                        }
                                                                        None => {
                                                                            w.insert(var,
                                                                            vec![WindTask {
                                                                                already_seen: false,
                                                                                kind: WindTaskKind::Fix(vec![wd.data])
                                                                            }]);
                                                                        }
                                                                    }
                                                                }
                                                                None => {
                                                                    send_now.push(wd.data);
                                                                }
                                                            }
                                                        }

                                                        let res = wind_tx_inner.send(send_now);
                                                        if res.is_err() {
                                                            error!(
                                                                "Could not send wind data to proxy sender. Are you sure the winds are connected?",
                                                            );
                                                        }
                                                    }

                                                    PacketKind::Heartbeat => {
                                                        debug!(
                                                            "Received Heartbeat from wind Minot TUI."
                                                        );
                                                    }
                                                    _ => {
                                                        warn!(
                                                            "Received unexpected packet from Minot TUI",
                                                            // packet.data
                                                        );
                                                    }
                                                },
                                                Err(e) => {
                                                    error!(
                                                        "Coordinator could not receive packet from Minot TUI: {e}"
                                                    );
                                                    return;
                                                }
                                            }
                                        },
                                        _ => {
                                            loop {
                                                match client_news.recv().await {
                                                    Ok((packet, _)) => {
                                                        match packet.data {
                                                            PacketKind::RegisterShipAtVar {
                                                                ship,
                                                                var,
                                                                kind,
                                                            } => {
                                                                rat_coord_tx.send(MinotTask::RegisterShipAtVar {ship,var,kind,},).unwrap();
                                                                client.send.send(Packet {header: sea::net::Header::default(),data: PacketKind::Acknowledge,}).await.unwrap();
                                                            }
                                                            PacketKind::VariableTaskRequest(
                                                                variable,
                                                            ) => {
                                                                    let (minot_actions, mut my_actions) = {
                                                                        let rat_rules_ref =
                                                                            rat_rules.read().unwrap();

                                                                            (sea::get_strategies(
                                                                                &rat_rules_ref,
                                                                                &minot_compare_name,
                                                                                variable.clone(),
                                                                                Some(&inner_name),
                                                                            ), sea::get_strategies(
                                                                                &rat_rules_ref,
                                                                                &inner_name,
                                                                                variable.clone(),
                                                                                None,
                                                                            ))
                                                                        
                                                                    };
                                                                for action in minot_actions {
                                                                    if !matches!(
                                                                        action,
                                                                        ActionPlan::Sail
                                                                    ) {
                                                                        rat_coord_tx.send(
                                                                    MinotTask::SendRatAction {
                                                                        ship_name: minot_compare_name
                                                                            .clone(),
                                                                        data: action,
                                                                    },
                                                                )
                                                                .unwrap();
                                                                    }
                                                                }


                                                                if my_actions.is_empty() {
                                                                    my_actions
                                                                        .push(ActionPlan::Sail);
                                                                }

                                                                debug!("sending actions: {:?}", my_actions);

                                                                // answer the client that asked
                                                                for action in my_actions {
                                                                    rat_coord_tx.send(MinotTask::SendRatAction {
                                                                        ship_name: inner_name.clone(),
                                                                        data: action,
                                                                    })
                                                                    .unwrap();
                                                                }

                                                                let mut winds =
                                                                    winds_inner.write().unwrap();

                                                                let mut asked_for_dynamic = false;
                                                                if let Some(wt) = winds.get_mut(&variable) { wt.iter_mut().for_each(|wte| {
                                                                        // TODO we saved many reguests here for the same var but only one will come through "already seen"
                                                                        if !wte.already_seen {
                                                                            match &mut wte.kind {
                                                                                WindTaskKind::Fix(wind_datas) => {
                                                                                        let ret = wind_tx_inner.send(wind_datas.clone()); // Forward to each listener of newly connected winds. They resolve the names.
                                                                                        match ret {
                                                                                            Ok(_) => {},
                                                                                            Err(e) => {
                                                                                                error!("Could not reach any turbine. Are you sure you have started and connected any? {e}");
                                                                                            },
                                                                                        }
                                                                                }
                                                                                WindTaskKind::Dynamic => {
                                                                                    if asked_for_dynamic {
                                                                                        wte.already_seen = true;
                                                                                        return; // only ask one time dynamic for the variable because minot tui sends all winds for this var with one request
                                                                                    }
                                                                                    asked_for_dynamic = true;

                                                                                    info!("asking Minot TUI for dyn for {}", &variable);
                                                                                    // ask Minot TUI to send the next fix command to us
                                                                                    let ret = rat_coord_tx.send(MinotTask::WindDynamicVarReq(variable.clone()));
                                                                                    match ret {
                                                                                        Ok(_) => {},
                                                                                        Err(e) => {
                                                                                            error!("Could not find connected Minot TUI for asking dynamic wind. {e}");
                                                                                        },
                                                                                    }
                                                                                }
                                                                            };
                                                                            wte.already_seen = true;
                                                                        }
                                                                    }); }

                                                                // set all other to be sent again
                                                                for (var, wind) in
                                                                    winds.iter_mut()
                                                                {
                                                                    if var == &variable {
                                                                        continue;
                                                                    }

                                                                    wind.iter_mut().for_each(
                                                                        |wte| {
                                                                            wte.already_seen =
                                                                                false;
                                                                        },
                                                                    );
                                                                }
                                                            }
                                                            PacketKind::Heartbeat => {}

                                                            _ => {
                                                                warn!(
                                                                    "Received unexpected packet {:?}",
                                                                    packet.data
                                                                );
                                                            }
                                                        }
                                                    }
                                                    Err(e) => {
                                                        match e {
                                                            tokio::sync::broadcast::error::RecvError::Closed => {
                                                                // disconnecting from network
                                                                if client.remove_rules_on_disconnect {
                                                                    let mut current_rules = rules_change_for_disconnect_inner.write().unwrap();
                                                                    current_rules.remove_client(&inner_name);
                                                                }
                                                            }, 
                                                            _ => {
                                                                error!(
                                                                    "Could not receive packet from client {inner_name}: {e}"
                                                                );
                                                            }
                                                        }
                                                        return;
                                                    }
                                                }
                                            }
                                        }
                                    };
                                });
                            }
                            sea::ShipKind::Wind(name) => {
                                let mut client_news = client.recv.subscribe();
                                let (acked_wind_tx, mut acked_wind_rx) =
                                    tokio::sync::mpsc::channel(5);
                                let inner_name_rx = name.clone();
                                tokio::spawn(async move {
                                    loop {
                                        match client_news.recv().await {
                                            Ok((packet, _)) => match packet.data {
                                                PacketKind::Acknowledge => {
                                                    if let Err(e) = acked_wind_tx.send(()).await {
                                                        error!(
                                                            "Could not passthrough ack trigger in wind receiver {inner_name_rx}: {e}"
                                                        );
                                                        return;
                                                    }
                                                }
                                                PacketKind::Heartbeat => {
                                                    debug!(
                                                        "Received Heartbeat from wind {inner_name_rx}."
                                                    );
                                                }
                                                _ => {
                                                    warn!(
                                                        "Unexpected packet from wind: {packet:?}"
                                                    );
                                                }
                                            },
                                            Err(e) => {
                                                match e {
                                                    tokio::sync::broadcast::error::RecvError::Closed => {}, // disconnected from network
                                                    _ => {
                                                        error!(
                                                            "Could not receive packet from wind client {inner_name_rx}: {e}"
                                                        );
                                                    }
                                                }
                                                return;
                                            }
                                        }
                                    }
                                });
                                let inner_name = name.clone();
                                let wind_coord_tx = coord_tx_new_client.clone();
                                tokio::spawn(async move {
                                    let mut sub = wind_tx_inner.subscribe();
                                    info!("Started wind forwarding for turbine: {}", &inner_name);
                                    while let Ok(data) = sub.recv().await {
                                        wind_coord_tx
                                            .send(MinotTask::SendWind {
                                                ship_name: inner_name.clone(),
                                                data,
                                            })
                                            .unwrap();
                                        acked_wind_rx.recv().await.unwrap(); // wait for wind to have sent everything. TODO add feedback channel for LH so it knows when wind is available again
                                    }
                                });
                            }
                        }
                    }
                    Err(e) => {
                        error!("Could not receive new client: {}", e);
                    }
                }
            }
        });

        // wait here until all clients are connected.
        clients_collected_rx.recv().await;

        let mut lock_next = locked_start;
        while let Some(task) = coord_rx.recv().await {
            match task {
                MinotTask::WindDynamicVarReq(var) => {
                    {
                        let minot_tui_connected = minot_client_connected.read().unwrap();
                        if !*minot_tui_connected {
                            error!(
                                "Wants to ask Minot TUI for wind for var {var} but is not connected."
                            );
                            continue;
                        }
                    }

                    let ret = coordinator
                        .rat_send(
                            COMPARE_NODE_NAME.to_owned(),
                            PacketKind::VariableTaskRequest(var),
                        )
                        .await;
                    if let Err(e) = ret {
                        error!("Could not send Dynamic Var Request to LH TUI: {e}");
                    }
                }
                MinotTask::AppendRule { variable, commands } => {
                    let mut current_rules = rules_changer.write().unwrap();
                    current_rules.insert(variable, commands);
                    info!("added new rule");
                }
                MinotTask::RulesClear => {
                    let mut current_rules = rules_changer.write().unwrap();
                    current_rules.clear();
                    info!("cleared all rules");
                }
                MinotTask::LockNext { unlock_first } => {
                    info!("locking next");
                    if unlock_first {
                        let clients = coordinator.rat_qs.read().await;
                        for (c, _) in clients.iter() {
                            if let Err(e) = coordinator
                                .rat_send(c.clone(), PacketKind::Acknowledge)
                                .await {
                                error!(
                                    "Error while sending ack for unlocking to Rat {}: {}",
                                    c, e
                                );
                                std::process::exit(1);
                            }
                        }
                    }

                    lock_next = true;
                }
                MinotTask::Unlock => {
                    let clients = coordinator.rat_qs.read().await;
                    for (c, _) in clients.iter() {
                        if let Err(e) = coordinator
                            .rat_send(c.clone(), PacketKind::Acknowledge)
                            .await {
                            error!("Error while sending ack for unlocking to Rat {}: {}", c, e);
                            std::process::exit(1);
                        }
                    }
                    lock_next = false;
                }
                MinotTask::SendWind { ship_name, data } => {
                    if let Err(e) = coordinator.blow_wind(ship_name.clone(), data).await {
                        error!("Error while blowing wind to {}: {}", ship_name, e);
                        std::process::exit(1);
                    }
                }
                MinotTask::SendRatAction {
                    ship_name,
                    mut data,
                } => {
                    {
                        let minot_tui_connected = minot_client_connected.read().unwrap();
                        if !*minot_tui_connected {
                            if ship_name == COMPARE_NODE_NAME {
                                continue;
                            }
                            data = match &data {
                                ActionPlan::Sail => data.clone(),
                                ActionPlan::Shoot { target, id } => {
                                    let ntargets = target
                                        .iter().filter(|&t| t != COMPARE_NODE_NAME).cloned()
                                        .collect::<Vec<_>>();
                                    if ntargets.is_empty() {
                                        ActionPlan::Sail
                                    } else {
                                        ActionPlan::Shoot { target: ntargets, id: *id,}
                                    }
                                }
                                ActionPlan::Catch { source, id: _ } => {
                                    if source == COMPARE_NODE_NAME {
                                        ActionPlan::Sail
                                    } else {
                                        data.clone()
                                    }
                                }
                            };
                        }
                    }

                    let lock_next = lock_next && ship_name != COMPARE_NODE_NAME;

                    if let Err(e) = coordinator
                        .rat_action_send(ship_name.clone(), data, lock_next)
                        .await {
                        error!("Error while sending action to Rat {}: {}", ship_name, e);
                        std::process::exit(1);
                    }
                }
                MinotTask::RegisterShipAtVar { ship, var, kind } => {
                    let mut current_rules = rules_changer.write().unwrap();
                    info!("Registering for topics {:?}", (&ship, &var, &kind));
                    current_rules.register(
                        var,
                        ship,
                        match kind {
                            sea::net::RatPubRegisterKind::Publish => {
                                mtc::RatPubRegisterKind::Publish
                            }
                            sea::net::RatPubRegisterKind::Subscribe => {
                                mtc::RatPubRegisterKind::Subscribe
                            }
                        },
                    );
                }
            }
        }
        debug!("coord_rx closed");
    });
}

pub fn get_clients(eval: &mtc::Evaluated) -> anyhow::Result<HashSet<String>> {
    let mut clients = HashSet::new();

    // ships from rules
    for (_, inner_clients) in eval.rules.raw().iter() {
        inner_clients.iter().for_each(|client| {
            if let Some(strat) = &client.strategy {
                match strat {
                    ActionPlan::Sail => {}
                    ActionPlan::Shoot { target, id: _ } => {
                        clients.extend(target.clone());
                    }
                    ActionPlan::Catch { source, id: _ } => {
                        clients.insert(source.clone());
                    }
                }
            };
            clients.insert(client.ship.clone());
        });
    }

    // find all winds using variables
    let winds = eval.vars.resolve("_wind")?;
    let winds = if let Some(winds) = winds {
        match winds {
            mtc::Rhs::Array(items)
                if items.iter().all(|item| matches!(**item, mtc::Rhs::Val(mtc::Val::StringVal(_))))
                 => 
            {
                items
                    .into_iter()
                    .map(|item| match *item {
                        mtc::Rhs::Val(mtc::Val::StringVal(wind)) => wind,
                        _ => {
                            unreachable!("Catched in higher match.")
                        }
                    })
                    .collect::<Vec<_>>()
            }
            mtc::Rhs::Val(mtc::Val::StringVal(single_wind)) => {
                vec![single_wind]
            }
            _ => {
                return Err(anyhow::anyhow!(
                    "Expected _wind variable to be String or Array<String>"
                ));
            }
        }
    } else {
        vec![]
    };

    clients.extend(winds);

    Ok(clients)
}

#[tokio::main(flavor = "multi_thread")]
pub async fn main() -> anyhow::Result<()> {
    let env = env_logger::Env::new().filter_or("RUST_LOG", "info");
    env_logger::Builder::from_env(env).init();

    let filepath = Args::parse().file;

    let eval = if let Some(fp) = filepath {
        let rules_file = std::fs::canonicalize(&fp)?;
        mtc::compile_file(&rules_file, None, None)?
    } else {
        mtc::Evaluated {
            rules: Rules::new(),
            wind: Vec::new(),
            vars: VariableHistory::new(Vec::new()),
        }
    };

    let locked_start = eval.vars.resolve("_start_locked")?;
    let locked_start = if let Some(rhs) = locked_start {
        match rhs {
            mtc::Rhs::Val(mtc::Val::BoolVal(locked)) => Ok(locked),
            _ => Err(anyhow!("Expected bool for _start_locked.")),
        }
    } else {
        Ok(false)
    }?;

    let clients = get_clients(&eval)?;
    run_coordinator(locked_start, clients, eval.rules);

    tokio::select! {
        _ = tokio::signal::ctrl_c() => {
            info!("Ctrl-C received. Shutting down...");
            return Ok(()) // all dangling tokio processes etc will be killed by the os
            // TODO ignores dissolving network currently
        }
    }
}
