name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

permissions:
  contents: write

jobs:

  rust-stable-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      # - name: Linting
        # run: cargo clippy --all-targets --features ros-native -- -D warnings
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang
          curl -sLo dlg_cut.zip "https://myshare.uni-osnabrueck.de/f/5faf4154af384854ab94?dl=1" && unzip dlg_cut.zip && rm dlg_cut.zip
      - name: Test
        run: cargo test --verbose

  linux-x86_64-musl:
    runs-on: ubuntu-latest
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu musl-tools libc6-dev-riscv64-cross gcc-arm-linux-gnueabihf
      - name: Build
        env:
          RUST_TARGET: x86_64-unknown-linux-musl
          TRIPLE: x86_64-linux-musl
        run: |
          rustup target add $RUST_TARGET
          RUSTFLAGS="-C target-feature=+crt-static" cargo build --target $RUST_TARGET --release --features ros2-native,ros1-native

      - name: "Archive binary"
        run: |
          TARGET=x86_64-unknown-linux-musl
          ARCHIVE_NAME=minot-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros1-native $ARCHIVE_NAME/wind-ros1-native
          cp target/$TARGET/release/wind-ros2-native $ARCHIVE_NAME/wind-ros2-native
          cp target/$TARGET/release/minot-coord $ARCHIVE_NAME/minot-coord
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          cp target/$TARGET/release/librat.a $ARCHIVE_NAME/librat.a
          cp rat/rat.h $ARCHIVE_NAME/rat.h
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-x86_64-unknown-linux-musl
          path: |
            *.tar.gz
            *.sha256

  linux-x86_64-gnu:
    runs-on: ubuntu-latest
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu musl-tools libc6-dev-riscv64-cross gcc-arm-linux-gnueabihf
      - name: Build
        env:
          RUST_TARGET: x86_64-unknown-linux-gnu
        run: |
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --features ros2-native,ros1-native

      - name: "Archive binary"
        run: |
          TARGET=x86_64-unknown-linux-gnu
          ARCHIVE_NAME=minot-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros1-native $ARCHIVE_NAME/wind-ros1-native
          cp target/$TARGET/release/wind-ros2-native $ARCHIVE_NAME/wind-ros2-native
          cp target/$TARGET/release/minot-coord $ARCHIVE_NAME/minot-coord
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          cp target/$TARGET/release/librat.a $ARCHIVE_NAME/librat.a
          cp target/$TARGET/release/librat.so $ARCHIVE_NAME/librat.so
          cp rat/rat.h $ARCHIVE_NAME/rat.h
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-x86_64-unknown-linux-gnu
          path: |
            *.tar.gz
            *.sha256

  linux-aarch64-gnu:
    runs-on: ubuntu-latest
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu musl-tools libc6-dev-riscv64-cross gcc-arm-linux-gnueabihf
      - name: Build
        env:
          RUST_TARGET: aarch64-unknown-linux-gnu
        run: |
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --features ros2-native,ros1-native

      - name: "Archive binary"
        run: |
          TARGET=aarch64-unknown-linux-gnu
          ARCHIVE_NAME=minot-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros1-native $ARCHIVE_NAME/wind-ros1-native
          cp target/$TARGET/release/wind-ros2-native $ARCHIVE_NAME/wind-ros2-native
          cp target/$TARGET/release/minot-coord $ARCHIVE_NAME/minot-coord
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          cp target/$TARGET/release/librat.a $ARCHIVE_NAME/librat.a
          cp target/$TARGET/release/librat.so $ARCHIVE_NAME/librat.so
          cp rat/rat.h $ARCHIVE_NAME/rat.h
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-aarch64-unknown-linux-gnu
          path: |
            *.tar.gz
            *.sha256

  linux-armv7-gnu:
    runs-on: ubuntu-latest
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu musl-tools libc6-dev-riscv64-cross gcc-arm-linux-gnueabihf
      - name: Build
        env:
          RUST_TARGET: armv7-unknown-linux-gnueabihf
        run: |
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --features ros2-native,ros1-native

      - name: "Archive binary"
        run: |
          TARGET=armv7-unknown-linux-gnueabihf
          ARCHIVE_NAME=minot-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros1-native $ARCHIVE_NAME/wind-ros1-native
          cp target/$TARGET/release/wind-ros2-native $ARCHIVE_NAME/wind-ros2-native
          cp target/$TARGET/release/minot-coord $ARCHIVE_NAME/minot-coord
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          cp target/$TARGET/release/librat.a $ARCHIVE_NAME/librat.a
          cp target/$TARGET/release/librat.so $ARCHIVE_NAME/librat.so
          cp rat/rat.h $ARCHIVE_NAME/rat.h
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-armv7-unknown-linux-gnueabihf
          path: |
            *.tar.gz
            *.sha256

  macos-aarch64:
    runs-on: macos-latest
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        env:
          RUST_TARGET: aarch64-apple-darwin
          TRIPLE: aarch64-apple-darwin
        run: |
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --features ros2-native,ros1-native

      - name: "Archive binary"
        run: |
          TARGET=aarch64-apple-darwin
          ARCHIVE_NAME=minot-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros1-native $ARCHIVE_NAME/wind-ros1-native
          cp target/$TARGET/release/wind-ros2-native $ARCHIVE_NAME/wind-ros2-native
          cp target/$TARGET/release/minot-coord $ARCHIVE_NAME/minot-coord
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          cp target/$TARGET/release/librat.a $ARCHIVE_NAME/librat.a
          cp target/$TARGET/release/librat.dylib $ARCHIVE_NAME/librat.dylib
          cp rat/rat.h $ARCHIVE_NAME/rat.h
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-aarch64-apple-darwin
          path: |
            *.tar.gz
            *.sha256

  macos-x86_64:
    runs-on: macos-latest
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        env:
          RUST_TARGET: x86_64-apple-darwin
          TRIPLE: x86_64-apple-darwin
        run: |
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --features ros2-native,ros1-native

      - name: "Archive binary"
        run: |
          TARGET=x86_64-apple-darwin
          ARCHIVE_NAME=minot-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros1-native $ARCHIVE_NAME/wind-ros1-native
          cp target/$TARGET/release/wind-ros2-native $ARCHIVE_NAME/wind-ros2-native
          cp target/$TARGET/release/minot-coord $ARCHIVE_NAME/minot-coord
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          cp target/$TARGET/release/librat.a $ARCHIVE_NAME/librat.a
          cp target/$TARGET/release/librat.dylib $ARCHIVE_NAME/librat.dylib
          cp rat/rat.h $ARCHIVE_NAME/rat.h
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-x86_64-apple-darwin
          path: |
            *.tar.gz
            *.sha256

  jazzy-linux-x86_64-gnu:
    runs-on: ubuntu-24.04
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
          sudo apt-get update --assume-yes && sudo apt-get install locales --assume-yes
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          sudo apt-get install software-properties-common --assume-yes
          # ROS2 Jazzy
          sudo add-apt-repository universe -y
          sudo apt-get update --assume-yes
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update --assume-yes && sudo apt-get install ros-dev-tools ros-jazzy-ros-base --assume-yes
          
      - name: Build
        env:
          RUST_TARGET: x86_64-unknown-linux-gnu
        run: |
          source /opt/ros/jazzy/setup.bash
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --package minot --bin minot --features embed-ros2-c
          cargo build --target $RUST_TARGET --release --package wind --bin wind-ros2-c  --features ros2-c

      - name: "Archive binary"
        run: |
          TARGET=x86_64-unknown-linux-gnu
          ARCHIVE_NAME=minot-jazzy-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros2-c $ARCHIVE_NAME/wind-ros2-c
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-jazzy-x86_64-unknown-linux-gnu
          path: |
            *.tar.gz
            *.sha256

  jazzy-linux-aarch64-gnu:
    runs-on: ubuntu-24.04-arm
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang
          sudo apt-get update --assume-yes && sudo apt-get install locales --assume-yes
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          sudo apt-get install software-properties-common --assume-yes
          # ROS2 Jazzy
          sudo add-apt-repository universe -y
          sudo apt-get update --assume-yes
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update --assume-yes && sudo apt-get install ros-dev-tools ros-jazzy-ros-base --assume-yes
          
      - name: Build
        env:
          RUST_TARGET: aarch64-unknown-linux-gnu
        run: |
          source /opt/ros/jazzy/setup.bash
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --package minot --bin minot --features embed-ros2-c
          cargo build --target $RUST_TARGET --release --package wind --bin wind-ros2-c  --features ros2-c

      - name: "Archive binary"
        run: |
          TARGET=aarch64-unknown-linux-gnu
          ARCHIVE_NAME=minot-jazzy-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros2-c $ARCHIVE_NAME/wind-ros2-c
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-jazzy-aarch64-unknown-linux-gnu
          path: |
            *.tar.gz
            *.sha256

  humble-linux-x86_64-gnu:
    runs-on: ubuntu-22.04
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang
          sudo apt-get update --assume-yes && sudo apt-get install locales --assume-yes
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          sudo apt-get install software-properties-common --assume-yes
          # ROS2 Humble
          sudo add-apt-repository universe -y
          sudo apt-get update --assume-yes
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update --assume-yes && sudo apt-get install ros-dev-tools ros-humble-ros-base --assume-yes
          
      - name: Build
        env:
          RUST_TARGET: x86_64-unknown-linux-gnu
        run: |
          source /opt/ros/humble/setup.bash
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --package minot --bin minot --features embed-ros2-c-humble
          cargo build --target $RUST_TARGET --release --package wind --bin wind-ros2-c  --features ros2-c,humble

      - name: "Archive binary"
        run: |
          TARGET=x86_64-unknown-linux-gnu
          ARCHIVE_NAME=minot-humble-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros2-c $ARCHIVE_NAME/wind-ros2-c
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-humble-x86_64-unknown-linux-gnu
          path: |
            *.tar.gz
            *.sha256

  humble-linux-aarch64-gnu:
    runs-on: ubuntu-22.04-arm
    needs: [rust-stable-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Dependencies
        run: |
          sudo apt-get install -y curl git unzip clang
          sudo apt-get update --assume-yes && sudo apt-get install locales --assume-yes
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          sudo apt-get install software-properties-common --assume-yes
          # ROS2 Humble
          sudo add-apt-repository universe -y
          sudo apt-get update --assume-yes
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update --assume-yes && sudo apt-get install ros-dev-tools ros-humble-ros-base --assume-yes
          
      - name: Build
        env:
          RUST_TARGET: aarch64-unknown-linux-gnu
        run: |
          source /opt/ros/humble/setup.bash
          rustup target add $RUST_TARGET
          cargo build --target $RUST_TARGET --release --package minot --bin minot --features embed-ros2-c-humble
          cargo build --target $RUST_TARGET --release --package wind --bin wind-ros2-c  --features ros2-c,humble

      - name: "Archive binary"
        run: |
          TARGET=aarch64-unknown-linux-gnu
          ARCHIVE_NAME=minot-humble-$TARGET
          ARCHIVE_FILE=$ARCHIVE_NAME.tar.gz

          mkdir -p $ARCHIVE_NAME
          cp target/$TARGET/release/wind-ros2-c $ARCHIVE_NAME/wind-ros2-c
          cp target/$TARGET/release/minot $ARCHIVE_NAME/minot
          tar czvf $ARCHIVE_FILE $ARCHIVE_NAME
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256

      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-humble-aarch64-unknown-linux-gnu
          path: |
            *.tar.gz
            *.sha256

  create-release:
    runs-on: ubuntu-latest
    needs: [macos-x86_64, macos-aarch64, linux-x86_64-musl, linux-aarch64-gnu, linux-armv7-gnu, linux-x86_64-gnu, jazzy-linux-x86_64-gnu, humble-linux-x86_64-gnu, humble-linux-aarch64-gnu, jazzy-linux-aarch64-gnu]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List downloaded artifacts (for verification)
        run: ls -R artifacts
      - name: Create Releae
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/**/*
          draft: true
          prerelease: false


